### PR TITLE
Misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`from upstream libdxfrw

### CODE REVIEW

**Comment by luzpaz** [comment]
please review

**Comment by luzpaz** [comment]
@JacobBarthelmeh  please review

**Comment by JacobBarthelmeh** [comment]
Hi Luzpaz,

Thank you for the pull request. wolfSSL is the most up to date and recent version of our embedded TLS product, located here (https://github.com/wolfSSL/wolfssl).

**Comment by luzpaz** [comment]
@JacobBarthelmeh will this PR then not get merged ?

**Comment by JacobBarthelmeh** [comment]
This PR will not get merged in. We appreciate the effort with opening the PR, but suggest using wolfSSL.

**Pull request closed without merging**
